### ISSUE TITLE
本番環境でデプロイが自動実行されるように改修を行う

### ISSUE THREAD

**Issue by keitakn** [nekochans/portfolio-frontend#69]
# Doneの定義
- 表題の件が実施されている事
- テストが終わった後にデプロイが実行されるようになっている事

 # 補足情報
以下のように `needs` で依存関係を持たせる事が出来るので、それで対応する。

```
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
 deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    needs: build
```
